### ISSUE TITLE
Error while installing on Mac

### ISSUE THREAD

**Issue by dangermouse198** [dstl/baleen#1]
Hi James, Team

I'm running Eclipse and trying to install Baleen, but keep getting build failure errors for the Collection Readers onwards, which means it isn't building half of the tool.

Please can you help?

Cheers,

DM

Results :

Failed tests:   testMultipleDirectories(uk.gov.dstl.baleen.collectionreaders.FolderReaderTest)
  testSubDirectoriesNonRecursive(uk.gov.dstl.baleen.collectionreaders.FolderReaderTest): expected:</[]var/folders/n2/4x13f...> but was:</[private/]var/folders/n2/4x13f...>
  testModifiedFile(uk.gov.dstl.baleen.collectionreaders.FolderReaderTest)
  testSubDirectories(uk.gov.dstl.baleen.collectionreaders.FolderReaderTest)
  testCreateFile(uk.gov.dstl.baleen.collectionreaders.FolderReaderTest)

Tests run: 19, Failures: 5, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Baleen ............................................ SUCCESS [  2.281 s]
[INFO] Baleen Core ....................................... SUCCESS [ 28.455 s]
[INFO] Baleen UIMA ....................................... SUCCESS [ 10.691 s]
[INFO] Baleen Resources .................................. SUCCESS [ 44.327 s]
[INFO] Baleen Annotators ................................. SUCCESS [01:07 min]
[INFO] Baleen Collection Readers ......................... FAILURE [ 27.084 s]
[INFO] Baleen Consumers .................................. SKIPPED
[INFO] Baleen History .................................... SKIPPED
[INFO] Baleen Runner ..................................... SKIPPED
[INFO] Baleen Javadoc .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:00 min
[INFO] Finished at: 2015-10-19T23:10:03+00:00
[INFO] Final Memory: 21M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project baleen-collectionreaders: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/User1/Desktop/baleen-master/baleen/baleen-collectionreaders/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :baleen-collectionreaders

**Comment by jbaker-dstl** [comment]
Hi dangermouse198,

Thanks for the feedback, I actually discovered the same issue on Friday when trying to build a version at home. I believe that the issue is to do with how the Mac handles temporary files and symlinks, so I will look into this and try to come up with a fix.

In the mean time, I believe it is just a case of the test failing, as opposed to there being any issues with the collection reader, so you should be able to build successfully by skipping that particular test.

James

**Comment by dangermouse198** [comment]
Hey James, thanks for looking into this issue!  Macs just have to be different, don't they!  Does this error occur in other Unix based operating systems?

Please can you tell me how I can skip the test and install the rest of the package in the meantime? I'm keen to get it up and running so I can actually test some data :)

I'm using Eclipse to install the package.

Kind regards,

dm

**Comment by jbaker-dstl** [comment]
No, this appears to be specific to Macs as we've tested it on Unix without any issues.

You can either skip all tests (in Eclipse, you can do this by checking the Skip Tests box in the Maven run configuration), or just that one by adding the `@Ignore` annotation to the test in the source code.

That said, have you considered just using the pre-built version available on the Releases tab?

**Comment by dangermouse198** [comment]
Hi, no idea it was available that way! I'll give the @ignore a try first, then the pre-built version if I fail.

Thanks!

Dm
