### ISSUE TITLE
Improve cleaning based on semantic type

### ISSUE THREAD

**Issue by chrisflatley** [dstl/baleen#11]
uk.gov.dstl.baleen.annotators.cleaners.helpers.AbstractNestedEntities will merge based on the first entity found (or least confidence).

Perhaps it should also consider the semantic type, a more specific type (eg Entity vs Person) should pick the person (for the same confidence)

**Comment by jbaker-dstl** [comment]
I'm not sure if it will merge two entities of different types, I think they have to be the same?

**Comment by chrisflatley** [comment]
Sorry that's correct. I was thinking this would be an additional mode / special case for two entities which are subtypes of one another. 

Perhaps the current type system isn't complex enough to warrant it though.

**Comment by jbaker-dstl** [comment]
Possibly something to think about in the future. As you say, I don't think our type system is complex enough at the moment for this to be an issue.
