### ISSUE TITLE
JavaDoc doesn't launch on Mac

### ISSUE THREAD

**Issue by dangermouse198** [dstl/baleen#13]
Hi James,

I reinstalled Baleen 2.1.0 on my MacBook Pro and tried to launch the JavaDoc, but it isn't launching.  There's an error, but that's all it is saying.  Baleen 2.1.0 .JAR file is in the same directory as the JavaDoc executable and that doesn't launch either: The Terminal reports it was unable to access the .JAR file.  What am I doing wrong please?

DM

**Comment by wozzam** [comment]
Check for spaces in your path.

**Comment by jbaker-dstl** [comment]
As @wozzam said, there was a bug that prevented Javadoc working in Baleen 2.1.0 if there was a space in the path (see Issue #8). This has been fixed in later snapshot releases, but the temporary fix if you don't want to build your own release from source is to use a path without spaces.
