### ISSUE TITLE
Does not build on openjdk 8

### ISSUE THREAD

**Issue by stuartmarsden** [dstl/baleen#15]
Fails to build on openjdk 8. I did not spend time figuring out why but switched to oracle jdk. You should make a note in the ReadMe saying that it must be Oracle and not OpenJDK.

**Comment by jbaker-dstl** [comment]
Thanks @stuartmarsden, I will try to confirm this and then see if it's something that can be fixed or otherwise add a note to the README file.

**Comment by jbaker-dstl** [comment]
I've been unable to find a suitable system with OpenJDK 8 to test this on, so for the time being I will update the README file.

**Comment by stuartmarsden** [comment]
I can confirm the release jar seems to run just fine on openJDK but just will not build with it. The README is therefore accurate now.
