### ISSUE TITLE
Building to include Javadoc from command-line

### ISSUE THREAD

**Issue by cmacdonald** [dstl/baleen#31]
Hi,

I tried to build from the command line, but there is no -javadoc.jar file placed in the target directory. Even if I remove the comment from the baleen-javadoc/pom.xml file to ensure that a javadoc Jar file is created, it doesnt contain all the files that are expected by the Core webapp UI.

Any advices?

**Comment by jbaker-dstl** [comment]
What command did you use? You need to run javadoc:aggregate-jar as the Maven target to build the Javadoc.

**Comment by cmacdonald** [comment]
Thanks that was the hint I needed. Perhaps this issue should then suggest amending the BUILD.md to document that.

**Comment by jbaker-dstl** [comment]
Feel free to submit a change to that affect if you wish.
