### ISSUE TITLE
Baleen tests fail with OpenJDK 8

### ISSUE THREAD

**Issue by StuJohn** [dstl/baleen#40]
The Baleen "requirements" suggest Oracle JDK but also just say that Baleen works with Java 8.

I've tried compiling with OpenJDK, but Maven fails because of a test failure. Baleen doesn't require JavaFX anywhere, but the [testComponents() unit test for AbstractComponentApiServletTest](https://github.com/dstl/baleen/blob/ea7555eea2fc8d4deac387666711abde7ca35ec1/baleen/baleen-core/src/test/java/uk/gov/dstl/baleen/core/web/servlets/AbstractComponentApiServletTest.java#L45-L70) uses JavaFX for its example data. OpenJDK doesn't include JavaFX.

I've managed to build Baleen by commenting out the entire contents of that test. It would be helpful if Baleen's tests didn't depend on proprietary classes that aren't in OpenJDK when the core functionality does not require those classes.

**Comment by jbaker-dstl** [comment]
A fair point, this has been fixed and will be included in the next future SNAPSHOT release.

**Comment by jbaker-dstl** [comment]
Addressed in Baleen 2.4
