### ISSUE TITLE
Landing page for Baleen server references 2.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by jamesdbaker** [dstl/baleen#77]
The current landing page for the Baleen server (the page that appears when you go to http://localhost:6413) references baleen-`2.5.0-SNAPSHOT.jar` in the commands, but should now reference `baleen-2.6.0-SNAPSHOT.jar` (and just `baleen-2.6.0.jar` once released).

**Comment by JohnDaws** [comment]
Fixed for Baleen 2.6.0
