### ISSUE TITLE
Incorrect normalisation factor for square inches

### ISSUE THREAD

**Issue by jbaker-nca** [dstl/baleen#85]
https://github.com/dstl/baleen/blob/67976e105eb34d9decaa03a091896cc7c8ef3c51/baleen-annotators/src/main/java/uk/gov/dstl/baleen/annotators/regex/Area.java#L25

The above line is out by a factor of 10, and should be `0.00064516`

**Comment by JohnDaws** [comment]
Thank you for fixing this issue. I'll accepted the pull request but will leave the issue open as a reminder to sort the unit tests out so that this error would have been caught.
